"""
REQUIRED INPUT FILES

1. PRODUCT_DETAILS_PRE.csv
2. PRODUCT_BRAND_PRE.csv
3. PRODUCT_CATEGORY_PRE.csv
4. PRODUCT_COUNTRY.csv

Will be generated:
1. STAFF_DETAILS.csv
2. CUSTOMER_DETAILS.csv
3. CUSTOMER_CART_ITEMS.csv
4. CUSTOMER_PURCHASE_INSTANCE.csv
5. CUSTOMER_PURCHASE_INSTANCE_ITEMS.csv
6. PRODUCT_DETAILS.csv
7. PRODUCT_BRAND.csv
8. PRODUCT_CATEGORY.csv

Will not be modified, can use as is:
1. PRODUCT_COUNTRY.csv
"""

# fairprice scraper
FILE_PRODUCT_MISSING_FIELDS = "PRODUCT_DETAILS_PRE.csv" # missing active, created_at, modified_at, modified_by
FILE_PRODUCT_BRAND_MISSING_FIELDS = "PRODUCT_BRAND_PRE.csv"  # missing active, created_at, modified_at, modified_by
FILE_PRODUCT_CATEGORY_WRONG_FIELDS = "PRODUCT_CATEGORY_PRE.csv"  # missing active, has unintended field url
FILE_PRODUCT_COUNTRY = "PRODUCT_COUNTRY.csv"

# customer generator (not final)
FILE_CUSTOMER_DETAILS_UNORDERED = "CUSTOMER_DETAILS_UNORDERED.csv"

# staff generator (final)
FILE_STAFF_DETAILS = "STAFF_DETAILS.csv"

# customer transaction generator (not final)
FILE_CUSTOMER_PURCHASE_INSTANCE_UNORDERED = "CUSTOMER_PURCHASE_INSTANCE_UNORDERED.csv"  # unused
FILE_CUSTOMER_PURCHASE_INSTANCE_ITEMS_UNORDERED = "CUSTOMER_PURCHASE_INSTANCE_ITEMS_UNORDERED.csv"  # unused

# customer cart generator (not final)
FILE_CUSTOMER_CART_ORDERED = "CUSTOMER_CART_ITEMS_ORDERED.csv"

# all other final dataframes
FILE_CUSTOMER_DETAILS_ORDERED = "CUSTOMER_DETAILS.csv"
FILE_CUSTOMER_PURCHASE_INSTANCE_ORDERED = "CUSTOMER_PURCHASE_INSTANCE.csv"
FILE_CUSTOMER_PURCHASE_INSTANCE_ITEMS_ORDERED = "CUSTOMER_PURCHASE_INSTANCE_ITEMS.csv"
FILE_CUSTOMER_CART_RANDOM = "CUSTOMER_CART_ITEMS.csv"
FILE_PRODUCT_FINAL = "PRODUCT_DETAILS.csv"
FILE_PRODUCT_BRAND_FINAL = "PRODUCT_BRAND.csv"
FILE_PRODUCT_CATEGORY_FINAL = "PRODUCT_CATEGORY.csv"
